eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082

spring:
  application:
    name: collection-service
  webClient:
    accountService:
      baseUrl: http://localhost:8187
  datasource:
    url: jdbc:mariadb://localhost/admin_db
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MySQL
    database-platform: org.hibernate.dialect.MySQLDialect
  springdoc:
    swagger-ui:
      path: /api-docs  # Set a custom path for Swagger UI (optional)
      configurationUrl: "http://localhost/api-docs"
  users:
    app:
    client:
      origin: http://localhost:4200/


